package com.example.pinatlas.model

import android.location.Location
import com.google.firebase.firestore.IgnoreExtraProperties;
import com.google.firebase.firestore.ServerTimestamp
import java.time.LocalDateTime
import kotlin.collections.ArrayList

@IgnoreExtraProperties
class Place {
    var placeId: String = ""                       // Auto populate ID
    // Properties of a place for firestore
    var name: String? = null                        // Name of the location
    var address: String? = null                     // Address of location
    var busyTimes: ArrayList<String>? = null       // Array of busy times
    var phoneNumber: String? = null                // Phone number as string
    var rating: Float? = null                       // Google Maps rating
    var types: ArrayList<String>? = null            // Type (museum, hotel, etc...)
    var openingHours: ArrayList<String>? = null    // Google Maps array of hours of operation
    var permanentlyClosed: Boolean? = null         // True if location is permanently closed
    var photos: ArrayList<String>? = null           // URL of photos from google maps
    var coordinates: Location? = null               // Coordinates of location

    @ServerTimestamp
    var last_updated: LocalDateTime? = null         // Generated by Firebase, last updated

    constructor()

    constructor(
        place_id: String,
        name: String?,
        address: String?,
        busy_times: ArrayList<String>?,
        phone_number: String?,
        rating: Float?,
        types: ArrayList<String>?,
        opening_hours: ArrayList<String>?,
        permanently_closed: Boolean?,
        photos: ArrayList<String>?,
        coordinates: Location?
    ) {
        this.placeId = place_id
        this.name = name
        this.address = address
        this.busyTimes = busy_times
        this.phoneNumber = phone_number
        this.rating = rating
        this.types = types
        this.openingHours = opening_hours
        this.permanentlyClosed = permanently_closed
        this.photos = photos
        this.coordinates = coordinates
    }


}